-- 1. Criação do Banco de Dados
CREATE DATABASE IF NOT EXISTS gestao_projetos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gestao_projetos;

-- 2. Tabela USUARIO
CREATE TABLE USUARIO (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    login VARCHAR(50) UNIQUE NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    Função VARCHAR(50)
);

-- 3. Tabela PROJETOS
CREATE TABLE PROJETOS (
    ID_PROJETO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SUPERVISOR VARCHAR(100),
    ID_EQUIPE INT,
    DESCRIÇÃO TEXT,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR(50)
);

-- 4. Tabela EQUIPE
CREATE TABLE EQUIPE (
    id_equipe INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    id_USUARIO INT,
    id_PROJETO INT,
    FOREIGN KEY (id_USUARIO) REFERENCES USUARIO(Id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (id_PROJETO) REFERENCES PROJETOS(ID_PROJETO) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Adiciona a Chave Estrangeira ID_EQUIPE na tabela PROJETOS após a criação da tabela EQUIPE
ALTER TABLE PROJETOS
ADD CONSTRAINT fk_projetos_equipe
FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(id_equipe) ON DELETE SET NULL ON UPDATE CASCADE;

-- 5. Tabela TAREFA
CREATE TABLE TAREFA (
    ID_TAREFA INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT,
    data_inicio DATE,
    prazo DATE,
    prioridade VARCHAR(20),
    status VARCHAR(50),
    id_projeto INT,
    id_responsavel INT,
    FOREIGN KEY (id_projeto) REFERENCES PROJETOS(ID_PROJETO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_responsavel) REFERENCES USUARIO(Id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 6. Tabela ANEXO
CREATE TABLE ANEXO (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    tarefa_id INT NOT NULL,
    url_arquivo VARCHAR(255) NOT NULL,
    nome_arquivo VARCHAR(150) NOT NULL,
    tipo_arquivo VARCHAR(50),
    FOREIGN KEY (tarefa_id) REFERENCES TAREFA(ID_TAREFA) ON DELETE CASCADE ON UPDATE CASCADE
);